# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_title',
            field=models.TextField(max_length=200),
        ),
    ]
