# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0002_auto_20160628_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(max_length=200000),
        ),
    ]
