# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0003_auto_20160628_2018'),
        ('overflow', '0002_auto_20160628_2016'),
    ]

    operations = [
    ]
