# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0004_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='netvotes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='netvotes',
        ),
    ]
