# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0005_auto_20160628_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='anonymous@pandora.com', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.CharField(default='anonymous@pandora.com', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='question_detail',
            field=models.TextField(default='no detail', max_length=200000),
        ),
    ]
