# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0007_auto_20160629_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='userID',
        ),
        migrations.AddField(
            model_name='comment',
            name='answer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='overflow.Answer'),
        ),
    ]
