# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0008_auto_20160629_1030'),
        ('overflow', '0008_remove_question_userid'),
    ]

    operations = [
    ]
