# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0009_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=20000)),
                ('author', models.CharField(default='anonymous@pandora.com', max_length=200)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Question_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=20000)),
                ('author', models.CharField(default='anonymous@pandora.com', max_length=200)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overflow.Question')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='author',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='upvotes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='answer',
        ),
        migrations.AddField(
            model_name='answer_comment',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overflow.Answer'),
        ),
    ]
