# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0010_auto_20160629_1130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer_Comment',
            new_name='AnswerComment',
        ),
        migrations.RenameModel(
            old_name='Question_Comment',
            new_name='QuestionComment',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='question',
        ),
    ]
