# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0011_question_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='userID',
        ),
    ]
