# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0012_remove_question_userid'),
        ('overflow', '0010_auto_20160629_1130'),
    ]

    operations = [
    ]
