# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0013_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.CharField(default='anonymous@pandora.com', max_length=200),
        ),
        migrations.AddField(
            model_name='answer',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='pub_date',
            field=models.DateTimeField(default='1/1/1950', verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='answer',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
