# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0012_auto_20160629_1416'),
        ('overflow', '0016_auto_20160629_1358'),
    ]

    operations = [
    ]
