# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0008_auto_20160629_2107'),
        ('overflow', '0019_auto_20160629_1430'),
    ]

    operations = [
    ]
