# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0020_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='userID',
        ),
        migrations.AddField(
            model_name='comment',
            name='userID',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='userID',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
