# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0021_auto_20160629_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='userID',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
